export default {
  login: "JardiinWD",
  id: 93372660,
  node_id: "U_kgDOBZDA9A",
  avatar_url: "https://avatars.githubusercontent.com/u/93372660?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/JardiinWD",
  html_url: "https://github.com/JardiinWD",
  followers_url: "https://api.github.com/users/JardiinWD/followers",
  following_url: "https://api.github.com/users/JardiinWD/following{/other_user}",
  gists_url: "https://api.github.com/users/JardiinWD/gists{/gist_id}",
  starred_url: "https://api.github.com/users/JardiinWD/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/JardiinWD/subscriptions",
  organizations_url: "https://api.github.com/users/JardiinWD/orgs",
  repos_url: "https://api.github.com/users/JardiinWD/repos",
  events_url: "https://api.github.com/users/JardiinWD/events{/privacy}",
  received_events_url: "https://api.github.com/users/JardiinWD/received_events",
  type: "User",
  site_admin: false,
  name: "Alessandro Pecorilla",
  company: null,
  blog: "https://www.linkedin.com/in/alessandro-pecorilla-8a98b7196",
  location: "San Paolo d'Argon - BG (IT)",
  email: null,
  hireable: null,
  bio: "Alessandro Pecorilla | 27 | Bergamo (IT) | Junior MERN Developer 💻 | Desktop PC Assembler 🖥",
  twitter_username: null,
  public_repos: 78,
  public_gists: 0,
  followers: 4,
  following: 7,
  created_at: "2021-10-29T07:48:19Z",
  updated_at: "2022-10-27T12:25:20Z"
};
